// flow-typed signature: a7ecf547678ab1f8bbc03cd687aeb8e7
// flow-typed version: <<STUB>>/redux-thunk_v2.2.0/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-thunk'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

import type { Middleware } from "redux";

declare module 'redux-thunk' {
  declare module.exports: Middleware;
}
